In [1]:
from ode_funs_vec import ode_funs
import numpy as np
import ode_funs_vec

In [2]:
N=3
J=np.ones((N,N))
J=np.random.rand(N,N)
np.fill_diagonal(J,0)
print(J)
eps=np.random.rand(N)
U=0,
gamma=np.random.rand(N)
ode_class=ode_funs(N, eps, J, U, gamma=gamma, Diss=None) 

[[0.00000000e+00 1.47608966e-01 5.15523739e-01]
 [4.88454124e-05 0.00000000e+00 9.46270002e-01]
 [4.35561191e-01 9.53820168e-01 0.00000000e+00]]


In [3]:

s, ss = ode_class.generate_full_op_list() 
index=ode_class.flat_index(s, ss, index={})
print(index)
leng=3*N+9*N**2
print(leng)

{'z': array([[0],
       [1],
       [2]]), '+': array([[3],
       [4],
       [5]]), '-': array([[6],
       [7],
       [8]]), 'zz': array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]]), 'z+': array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]]), 'z-': array([[27, 28, 29],
       [30, 31, 32],
       [33, 34, 35]]), '+z': array([[36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]]), '++': array([[45, 46, 47],
       [48, 49, 50],
       [51, 52, 53]]), '+-': array([[54, 55, 56],
       [57, 58, 59],
       [60, 61, 62]]), '-z': array([[63, 64, 65],
       [66, 67, 68],
       [69, 70, 71]]), '-+': array([[72, 73, 74],
       [75, 76, 77],
       [78, 79, 80]]), '--': array([[81, 82, 83],
       [84, 85, 86],
       [87, 88, 89]])}
90


In [4]:
Y=np.random.rand(leng)
print(Y[index['zz']])

[[0.73252763 0.4583064  0.51506269]
 [0.17327964 0.54600301 0.35455604]
 [0.1748964  0.72774187 0.04522011]]


In [5]:
A=ode_funs_vec.sum_li(J,Y,index,'-+z')
print(A)

[[8.00535188e-01 8.25405647e-01 1.07338404e-01]
 [1.73526120e-02 3.74333395e-01 1.39529917e-01]
 [7.62506441e-02 2.99964570e-05 6.57220883e-01]]


In [6]:
B=ode_funs_vec.sum_li_loop(J,Y,index,'-+z')
print(B)

[[8.00535188e-01 8.25405647e-01 1.07338404e-01]
 [1.73526120e-02 3.74333395e-01 1.39529917e-01]
 [7.62506441e-02 2.99964570e-05 6.57220883e-01]]


In [7]:
for i in range(1):
    print(A[i]-B[i]) 
    print('\n')

[0.00000000e+00 0.00000000e+00 2.77555756e-17]




In [8]:
print(A-B)

[[ 0.00000000e+00  0.00000000e+00  2.77555756e-17]
 [ 1.38777878e-17 -2.77555756e-16  0.00000000e+00]
 [-1.38777878e-17 -6.38561198e-17  0.00000000e+00]]


In [9]:
C=ode_funs_vec.sum2(J,Y,index,'-+')
print(C)

[[0.25922997]
 [0.2892246 ]
 [0.51029576]]


In [10]:
D=ode_funs_vec.sum2_loop(J,Y,index,'-+')
print(D)

[[0.25922997]
 [0.2892246 ]
 [0.51029576]]
